version: '3'
services:

  backend:
    networks:
      - back-net
    container_name: backend
    image: kp-back-img
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    env_file:
      - .env

  frontend:
    networks:
      - front-net
    container_name: frontend
    image: kp-front-img
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80 

  postgres:
    networks:
      - back-net
    container_name: postgres
    restart: unless-stopped
    image: postgres:14-alpine
    volumes:
      - postgress_data:/var/lib/postgresql/data
    env_file:
      - .env

  adminer:
    networks:
      - back-net
    container_name: adminer
    restart: unless-stopped
    image: adminer
    ports:
      - 8081:8080

volumes:
  postgress_data:

networks:
  back-net:
  front-net: